### ISSUE TITLE
Empty html5bp_script.js crashes yuicompressor

### ISSUE THREAD

**Issue by giero** [phiamo/MopaBootstrapBundle#1032]
Hello,

During dumping assets with yuicompressor on prod environment empty `html5bp_script.js` crashes yuicompressor.

My config for prod:

```
assetic:
    filters:
        yui_css:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/../vendor/nervo/yuicompressor/yuicompressor.jar"
            apply_to: "\.js$"
```

For the curious it looks like this: http://pastebin.com/36erinz0

Interesting is that this file is added to assets in `MopaBootstrapBundle::base_initializr.html.twig` - I do not use it at all. My `layout.html.twig` inherits from `MopaBootstrapBundle::base.html.twig`. Is there any way to disable/prevent dumping assets from `MopaBootstrapBundle::base_initializr.html.twig`?
