### ISSUE TITLE
icons not displayed - bootstrap 3.3+ sass version

### ISSUE THREAD

**Issue by nska02** [phiamo/MopaBootstrapBundle#1114]
Hi,

I'm a "fresh" (few months) newbie with symfony and I tried to setup this bundle: everything seems to work but **can't make the glyphicons work** (been on it for 24h).

* Followed all instructions to use this bundle with bootstrap (3.3+) sass version (using compass as parser), resulting in:

**config.yml**
```yml
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
#     bundles: []
#     java: /usr/bin/java
    filters:
        cssrewrite: ~
        compass:
            bin: /usr/local/bin/compass
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor.jar
mopa_bootstrap:
    icons:
        icon_set: glyphicons
        shortcut: icon
```

**layout.html.twig**
```twig
{% extends 'MopaBootstrapBundle::base_sass_3.2.html.twig' %}

{% block head_style %}
    {% stylesheets
        filter='compass, cssrewrite, ?yui_css' 
        'bundles/mopabootstrap/sass/mopabootstrapbundle-3.2.scss'
        'bundles/axcore/css/AXCoreLayout.scss'
    %}
        <link rel="stylesheet" href="{{ asset_url }}" type="text/css" media="screen" />
    {% endstylesheets %}
{% endblock head_style %}

{% block head_script %}
    {% javascripts
        filter='?yui_js'
        '@AXCoreBundle/Resources/public/jquery/jquery-1.11.3.min.js'
    %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock head_script %}

{% block foot_script_assetic %}
    {% javascripts 
        filter='?yui_js'
        '@MopaBootstrapBundle/Resources/public/bootstrap-sass/assets/javascripts/bootstrap/tooltip.js'
        '@MopaBootstrapBundle/Resources/public/bootstrap-sass/assets/javascripts/bootstrap/*.js'
        '@MopaBootstrapBundle/Resources/public/js/mopabootstrap-collection.js'
        '@MopaBootstrapBundle/Resources/public/js/mopabootstrap-subnav.js'
        '@AXCoreBundle/Resources/public/js/*'
    %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
    {% endjavascripts %}
{% endblock foot_script_assetic %}
// some other stuff
```

* But can't get the resource:

*The requested URL /bundles/mopabootstrap/fonts/bootstrap/glyphicons-halflings-regular.woff2 was not found on this server.*

Similar messages for woff and ttf.

Maybe I'm desperately blind or tired but would much appreciate support on this.
Thanks!
