### ISSUE TITLE
unable to turn off rightmenu

### ISSUE THREAD

**Issue by nysander** [phiamo/MopaBootstrapBundle#161]
this do not work and throw exception:

An exception has been thrown during the rendering of a template ("Menu rightmenu not found!") in MopaBootstrapBundle::base.html.twig at line 110.

```
    fund.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { leftmenu: @fund.navbar_main_menu= }
            - {}
            - { fixedTop: false, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: mainnavbar }
```

this works:

```
    fund.navbar:
        class: '%mopa_bootstrap.navbar.generic%'
        scope: request
        arguments:
            - { leftmenu: @fund.navbar_main_menu=,  rightmenu: ''}
            - {}
            - { fixedTop: false, isFluid: false }
        tags:
            - { name: mopa_bootstrap.navbar, alias: mainnavbar }
```
