### ISSUE TITLE
MopaBootsrapBundle

### ISSUE THREAD

**Issue by boldtrn** [phiamo/MopaBootstrapBundle#500]
Hi,

I am trying to set up MopaBootstrapBundle with lessPhp. When I install LessPhp like described here: http://isometriks.com/using-less-with-symfony2 (Actually all Tutorials are equal)

I allways get the Error: `There is no "less" filter.`

My Assectic configuration looks like this:

```
filters:
        lessphp:
          file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
          apply_to: "\.less$"
          # Formatter options: compressed, lessjs, classic
          formatter: "compressed"
          preserve_comments: false
```

Is it possible to use MopaBootstrap with lessphp?
