### ISSUE TITLE
[Collection Widget] - Can't be disabled.

### ISSUE THREAD

**Issue by zender** [phiamo/MopaBootstrapBundle#636]
How can I disable collection widget. I tried with:

``` yml
mopa_bootstrap:
    version: 3
    navbar: ~
    form: 
      render_fieldset: false
      show_legend: false
      render_collection_item: false #disable
      checkbox_label: 'label'
      horizontal_input_wrapper_class: "col-lg-6"
```

but _render_collection_item_  does not work.
