### ISSUE TITLE
Widget help popovers don't work when trigger is set to focus

### ISSUE THREAD

**Issue by marshmn** [phiamo/MopaBootstrapBundle#793]
There is a configuration option that can be set to control the trigger for a widget's help popover:

``` YAML
mopa_bootstrap:
    form:
        help_widget:
            popover:
                trigger: click
```

Setting the trigger to 'focus' however does not work. This appears to be due to the fact that the data attributes get set on a div element surrounding the widget rather than on the widget that gets focused itself. Therefore the popover fails to be shown.

One possible solution to this would be to set the 'data-selector' attribute to target the actual widget.
