### ISSUE TITLE
InvalidConfigurationException: Unrecognized options "horizontal" under "mopa_bootstrap.form"

### ISSUE THREAD

**Issue by ghost** [phiamo/MopaBootstrapBundle#845]
I am new to Symfony2 and the extensions, so this might be my fault. I am trying to render my forms vertically. So I changed the config according to https://github.com/phiamo/MopaBootstrapBundle/blob/master/Resources/doc/configuration-reference.md

```
mopa_bootstrap:
    form:
        horizontal: false
        show_legend: false
        show_child_legend: false
        render_optional_text: false
        render_required_asterisk: true
```

But the horizontal option causes an error: 

```
InvalidConfigurationException: Unrecognized options "horizontal" under "mopa_bootstrap.form"
```

As you can see in my composer.json, I am using 3.0.0-beta-3

```
"mopa/bootstrap-bundle": "v3.0.0-beta3",
"twbs/bootstrap": "v3.0.0",
"knplabs/knp-paginator-bundle": "dev-master",
"knplabs/knp-menu-bundle": "dev-master",
"knplabs/knp-menu": "2.0.*@dev",
"knplabs/knp-snappy-bundle": "dev-master",
"craue/formflow-bundle": "dev-master",
"components/jquery": "1.11.*",
"leafo/lessphp": "0.4.0"
```

Was the horizontal option removed? If so, how do I render all elements of a form "vertically" (meaning label above input) without having to set horizontal => false on each of them?
