### ISSUE TITLE
Global horizontal form class

### ISSUE THREAD

**Issue by na-ji** [phiamo/MopaBootstrapBundle#871]
Hello !

When I want to change global class for horizontal form, the configuration is not used. This is my configuration. For the horizontal_label_class and horizontal_input_wrapper_class, it is not different from default configuration. 

``` yaml
mopa_bootstrap:
    form:
        horizontal: true
        horizontal_label_class: col-lg-3 col-sm-3 control-label
        horizontal_label_offset_class:  col-lg-offset-3
        horizontal_input_wrapper_class: col-lg-9 col-sm-9
        render_fieldset: false
        render_collection_item: true
        show_legend: false
    menu: ~
```

After rendering, there is only "control-label" as a class on my form's label. So how to globally change those classes ? 

Thanks !
