### ISSUE TITLE
definition of icon attribute for widget_remove_btn do not consider icon_set

### ISSUE THREAD

**Issue by cellulosa** [phiamo/MopaBootstrapBundle#920]
In my `config.yml` I am trying to setup an icon for the `widget_remove_btn` using:

```
mopa_bootstrap:
    form:
        collection:
            widget_remove_btn:
                label: Remove
                icon: trash-o
    icons:
        icon_set: fontawesome
```

However the icon gets never rendered because `{{ form(form) }}` generates `<span class="glyphicon glyphicon-trash-o"></span>` instead of `<i class="fa fa-trash-o"></i>`
